#!/usr/bin/env python3
"""Reproduce the bounded Patat (2006) V-band twilight correction for the shipped LUT."""

import hashlib
import math

import numpy as np
from verify_atmosphere import ROOT, Y, read, sky


def main():
    source = ROOT / "data/atmosphere/clear.bin"
    tables, _ = read(source)
    zero = 2.54e-6 / (math.pi / 648000) ** 2
    values = []
    for depression in np.linspace(5, 15, 401):
        x = depression - 5
        total = zero * 10 ** (-0.4 * (11.84 + 1.518 * x - 0.057 * x * x))
        scattered = sky(tables, 2.635, -depression, 90, 0) @ Y
        values.append(math.log((total - 0.0002475) / scattered))
    lines = [
        "#pragma once",
        "#include <array>",
        "",
        "// Generated by scripts/calibrate_twilight.py; format with scripts/format.py.",
        "// Natural night is subtracted before fitting scattered solar light.",
        f"// Clear LUT SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
        "namespace astro::photometry {",
        "inline constexpr std::array<double, 401> twilight_log_gain = {",
        *[f"    {value:.12f}," for value in values],
        "};",
        "} // namespace astro::photometry",
        "",
    ]
    target = ROOT / "include/astro/twilight_calibration.hpp"
    target.write_text("\n".join(lines))
    print(target)


if __name__ == "__main__":
    main()
