#!/usr/bin/env python3
"""Generate spectral coefficients for the pinned Bruneton Vulkan atmosphere."""

import argparse
import hashlib
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def manifest(folder):
    assets = {}
    headers = []
    for name in ["clear.bin", "hazy.bin"]:
        data = (folder / name).read_bytes()
        if data[:8] != b"ASTRAAT2":
            raise ValueError("Unsupported atmosphere cache")
        preset, orders, groups = struct.unpack_from("<3I", data, 76)
        headers.append(
            dict(
                name=name,
                preset=preset,
                scattering_orders=orders,
                wavelengths=groups * 3,
                source_id=data[8:72].decode(),
            )
        )
        assets[f"atmosphere/{name}"] = hashlib.sha256(data).hexdigest()
    output = dict(
        model="bruneton-spectral-v1",
        format="ASTRAAT2 / little-endian RGBA32F",
        upstream_commit="34f14e745cff948f4ca3157d1b62a445ffa7286f",
        profiles=headers,
        runtime_sha256=assets,
        solar_zenith_limit_degrees=120,
        dimensions=[[256, 64, 1], [256, 128, 32], [256, 128, 32], [64, 16, 1]],
    )
    (folder / "manifest.json").write_text(json.dumps(output, indent=2) + "\n")


def generate(count):
    if count < 3 or count % 3 or count > 96:
        raise ValueError("Wavelength count must be a multiple of three in [3, 96]")
    source = (ROOT / "vendor/bruneton/constants.h").read_text()

    def table(name):
        body = re.search(name + r"\[\d+\] = \{(.*?)\}", source, re.S)[1]
        return [float(value) for value in body.split(",") if value.strip()]

    cie = table("CIE_2_DEG_COLOR_MATCHING_FUNCTIONS")
    xyz = table("XYZ_TO_SRGB")
    earth = json.loads((ROOT / "vendor/bruneton/earth.json").read_text())

    def interpolate(values, wavelength, start, step):
        u = min(len(values) - 1, max(0, (wavelength - start) / step))
        i = min(len(values) - 2, int(u))
        return values[i] * (1 - (u - i)) + values[i + 1] * (u - i)

    def rgb(wavelength):
        sample = [interpolate(cie[c::4], wavelength, 360, 5) for c in (1, 2, 3)]
        return [sum(xyz[r * 3 + c] * sample[c] for c in range(3)) for r in range(3)]

    def vec(values, kind="vec3"):
        return kind + "(" + ", ".join(f"{x:.10e}" for x in values) + ")"

    step = 470 / count
    wavelengths = [360 + (i + 0.5) * step for i in range(count)] + [680, 550, 440]
    groups = [wavelengths[i : i + 3] for i in range(0, len(wavelengths), 3)]
    solar = [vec([interpolate(earth["kSolarIrradiance"], w, 360, 10) for w in g]) for g in groups]
    rayleigh = [vec([1.24062e-3 * (w / 1000) ** -4 for w in g]) for g in groups]
    ozone = [
        vec([300 * 2.687e20 / 15 * interpolate(earth["kOzoneCrossSection"], w, 360, 10) for w in g])
        for g in groups
    ]
    matrices = [vec([x * step * 683 for w in g for x in rgb(w)], "mat3") for g in groups[:-1]]
    sun_rgb = [
        sum(
            rgb(w)[c] * interpolate(earth["kSolarIrradiance"], w, 360, 10) * 683
            for w in range(361, 830)
        )
        for c in range(3)
    ]
    lines = [
        "// Generated by scripts/prepare_atmosphere.py; see vendor/bruneton/LICENSE.",
        "// clang-format off",
        f"const int SPECTRAL_GROUPS = {count // 3};",
        f"const vec3 SOLAR_ILLUMINANCE = {vec(sun_rgb)};",
    ]
    for name, kind, values in [
        ("SOLAR", "vec3", solar),
        ("RAYLEIGH", "vec3", rayleigh),
        ("OZONE", "vec3", ozone),
        ("TO_LUMINANCE", "mat3", matrices),
    ]:
        lines.append(
            f"const {kind} {name}[{len(values)}] = {kind}[](\n    "
            + ",\n    ".join(values)
            + "\n);"
        )
    lines.append("// clang-format on")
    (ROOT / "shaders/atmosphere_spectrum.glsl").write_text("\n".join(lines) + "\n")
    print(f"Generated {count} wavelength coefficients")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wavelengths", type=int, default=45)
    parser.add_argument("--manifest", type=Path, help="Write checksums after Vulkan generation")
    args = parser.parse_args()
    if args.manifest:
        manifest(args.manifest)
    else:
        generate(args.wavelengths)
