#!/usr/bin/env python3
"""Encode NASA's native 16K Gaia star-background data for the Vulkan renderer."""

import json
import os

import numpy as np
from bootstrap import ROOT, digest, download
from PIL import Image

SOURCE_PAGE = "https://svs.gsfc.nasa.gov/4851/"
SOURCE_URL = "https://svs.gsfc.nasa.gov/vis/a000000/a004800/a004851/milkyway_2020_16k_gal.exr"
SOURCE_SHA256 = "ee023f03e99466b3829117c15a001269ba32a3fecb6012d0b2d41f201c955351"
BACKGROUND_ID = "nasa-gaia-dr2-photometric-16k-v2"


def calibrate(image):
    from astropy import units as u
    from astropy_healpix import HEALPix

    reference_path = ROOT / "data/photometry/gambons-table3.json"
    reference = json.loads(reference_path.read_text())
    hp = HEALPix(nside=reference["healpix_nside"], order=reference["healpix_order"])
    # Enclose the nine published HEALPix cells in NASA's native Galactic map.
    xs, ys = np.arange(6090, 6170), np.arange(4040, 4100)
    longitude, latitude = np.meshgrid(
        (0.5 - (xs + 0.5) / 16384) * 360, (0.5 - (ys + 0.5) / 8192) * 180
    )
    cells = hp.lonlat_to_healpix(longitude * u.deg, latitude * u.deg)
    luminance = image[ys[:, None], xs[None, :]] @ [0.0722, 0.7152, 0.2126]
    weights = np.cos(np.radians(latitude))
    diffuse = np.array(
        [np.average(luminance[cells == k], weights=weights[cells == k]) for k in range(9)]
    )

    # The reference includes bright stars that NASA omits. Subtract catalogue
    # stars brighter than V=11.5 before fitting the diffuse map, not afterwards.
    dtype = np.dtype(
        [
            ("id", "<u8"),
            ("hip", "<u4"),
            ("flags", "<u4"),
            ("ra", "<f8"),
            ("dec", "<f8"),
            ("astrometry", "V40"),
            ("mag", "<f4"),
            ("bv", "<f4"),
            ("errors", "V16"),
        ]
    )
    catalogue = ROOT / "data/catalog/stars.bin"
    stars = np.fromfile(catalogue, dtype=dtype, offset=24)
    directions = np.array(
        [
            np.cos(stars["dec"]) * np.cos(stars["ra"]),
            np.cos(stars["dec"]) * np.sin(stars["ra"]),
            np.sin(stars["dec"]),
        ]
    )
    rotation = np.array(
        [
            [-0.0548755604, -0.8734370902, -0.4838350155],
            [0.4941094279, -0.4448296300, 0.7469822445],
            [-0.8676661490, -0.1980763734, 0.4559837762],
        ]
    )
    galactic = rotation @ directions
    longitude = np.degrees(np.arctan2(galactic[1], galactic[0]))
    selected = (longitude > 43) & (longitude < 47) & (abs(galactic[2]) < 0.025)
    stars, galactic = stars[selected], galactic[:, selected]
    cells = hp.lonlat_to_healpix(
        np.arctan2(galactic[1], galactic[0]) * u.rad, np.arcsin(galactic[2]) * u.rad
    )
    colour = np.clip((stars["bv"] + 0.1) / 0.75, -0.5, 5)
    g_minus_v = -0.02704 + 0.01424 * colour - 0.2156 * colour**2 + 0.01426 * colour**3
    visual = np.where(stars["flags"] & 16, stars["mag"] - g_minus_v, stars["mag"])
    flux = 2.54e-6 * 10 ** (-0.4 * visual)
    area = 4 * np.pi / (12 * reference["healpix_nside"] ** 2)
    foreground = np.array([flux[(cells == k) & (visual < 11.5)].sum() / area for k in range(9)])
    target = np.array(reference["photopic_radiance"]) * 683
    training = np.array(reference["training_pixels"])
    residual = target - foreground
    if np.any(residual <= 0):
        raise RuntimeError("Catalogue foreground exceeds the reference sky radiance")
    scale = float(
        np.dot(diffuse[training], residual[training]) / np.dot(diffuse[training], diffuse[training])
    )
    predicted = diffuse * scale + foreground
    report = dict(
        reference=str(reference_path.relative_to(ROOT)),
        reference_sha256=digest(reference_path),
        catalogue_sha256=digest(catalogue),
        radiance_scale_cd_m2=scale,
        training_pixels=reference["training_pixels"],
        validation_pixels=reference["validation_pixels"],
        reference_luminance=target.tolist(),
        catalogue_foreground=foreground.tolist(),
        nasa_linear_luminance=diffuse.tolist(),
        predicted_total=predicted.tolist(),
        relative_residual=(predicted / target - 1).tolist(),
    )
    header = ROOT / "include/astro/background_calibration.hpp"
    header.write_text(
        "#pragma once\n\n// Generated by scripts/prepare_background.py.\n"
        "namespace astro {\n"
        f"inline constexpr float background_radiance_scale = {scale:.12f}f;\n"
        "} // namespace astro\n"
    )
    return report


def prepare():
    # Only offline asset preparation needs an EXR decoder, not the application.
    os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"
    import cv2

    source = download("data/background/nasa-milkyway-2020-16k-gal.exr", SOURCE_URL, SOURCE_SHA256)
    image = cv2.imread(str(source), cv2.IMREAD_UNCHANGED)
    if image is None or image.shape != (8192, 16384, 3) or image.dtype != np.float32:
        raise RuntimeError("Expected NASA's 16384x8192 linear RGB EXR background")
    calibration = calibrate(image)

    # NASA separates the bright Hipparcos/Tycho foreground. Keep native texels:
    # no median, blur, sharpening or upscaling. Strips bound temporary memory.
    pixels = np.empty(image.shape, dtype=np.uint8)
    for y in range(0, image.shape[0], 64):
        rgb = image[y : y + 64, :, ::-1].copy()  # OpenCV decodes BGR.
        if not np.isfinite(rgb).all() or np.any(rgb < 0) or np.any(rgb > 1):
            raise RuntimeError("Non-finite or negative intensity in the source map")
        # Reversible sRGB storage only: no per-channel gain or highlight compression.
        rgb = np.where(rgb <= 0.0031308, rgb * 12.92, 1.055 * rgb ** (1 / 2.4) - 0.055)
        pixels[y : y + 64] = np.rint(np.clip(rgb, 0, 1) * 255).astype(np.uint8)
    del image

    # All longitudes at each pole converge to one direction. Average in linear
    # light; no smoothing is applied to any other row or across the map.
    for row in (0, pixels.shape[0] - 1):
        color = pixels[row].astype(np.float32) / 255
        color = np.where(color <= 0.04045, color / 12.92, ((color + 0.055) / 1.055) ** 2.4)
        color = color.mean(axis=0)
        color = np.where(color <= 0.0031308, color * 12.92, 1.055 * color ** (1 / 2.4) - 0.055)
        pixels[row] = np.rint(color * 255).astype(np.uint8)

    target = ROOT / "data/background/milky-way.png"
    Image.fromarray(pixels).save(target, compress_level=6)
    manifest = {
        "background_id": BACKGROUND_ID,
        "source_page": SOURCE_PAGE,
        "source_url": SOURCE_URL,
        "source_sha256": SOURCE_SHA256,
        "credit": (
            "NASA/Goddard Space Flight Center Scientific Visualization Studio; Ernie Wright. "
            "Gaia DR2: ESA/Gaia/DPAC."
        ),
        "license": "NASA media usage guidelines; underlying Gaia data acknowledgements apply",
        "license_url": "https://www.nasa.gov/nasa-brand-center/images-and-media/",
        "projection": "Galactic equirectangular; u = 0.5 - l/(2*pi), v = 0.5 - b/pi",
        "dimensions": [pixels.shape[1], pixels.shape[0]],
        "calibration": calibration,
        "processing": (
            "Native 16384x8192, no spatial filtering except linear-light polar-row averages; "
            "linear EXR decoded without highlight compression, sRGB8 PNG encoding; "
            "runtime linear-light mipmaps and optional 8x anisotropic filtering"
        ),
        "limitations": (
            "Gaia DR2 faint-star visualization with Hipparcos/Tycho foreground omitted; "
            "fixed distant background with one regional photopic normalization; "
            "not an all-sky radiometric survey or evolving star catalogue. "
            "NASA colour balance, Gaia survey artefacts and source pixel resolution remain; "
            "regional normalization includes diffuse Galactic and extragalactic light."
        ),
        "runtime_sha256": {"background/milky-way.png": digest(target)},
    }
    (target.parent / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Prepared {target}: {pixels.shape[1]}x{pixels.shape[0]}, SHA-256 {digest(target)}")


if __name__ == "__main__":
    prepare()
